create table if not exists public.scan_history (
  id bigint generated by default as identity primary key,
  input_type text not null check (input_type in ('message','link','screenshot')),
  content_preview text not null,
  risk_score integer not null check (risk_score between 0 and 100),
  risk_level text not null check (risk_level in ('LOW','MEDIUM','HIGH')),
  category text not null,
  result_json jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists scan_history_created_at_idx
  on public.scan_history (created_at desc);

alter table public.scan_history enable row level security;
